// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/pack": {
            "post": {
                "description": "Recebe pedidos com produtos e retorna a alocação em caixas disponíveis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Empacotamento"
                ],
                "summary": "Empacota produtos em caixas",
                "parameters": [
                    {
                        "description": "Lista de pedidos",
                        "name": "pedidos",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/controllers.PackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/controllers.PackResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "controllers.CaixaResponse": {
            "type": "object",
            "properties": {
                "caixa_id": {
                    "type": "string"
                },
                "produtos": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "controllers.PackRequest": {
            "type": "object",
            "properties": {
                "pedidos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Pedido"
                    }
                }
            }
        },
        "controllers.PackResponse": {
            "type": "object",
            "properties": {
                "pedidos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.PedidoResponse"
                    }
                }
            }
        },
        "controllers.PedidoResponse": {
            "type": "object",
            "properties": {
                "caixas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/controllers.CaixaResponse"
                    }
                },
                "pedido_id": {
                    "type": "integer"
                }
            }
        },
        "models.Dimensoes": {
            "type": "object",
            "properties": {
                "altura": {
                    "type": "number"
                },
                "comprimento": {
                    "type": "number"
                },
                "largura": {
                    "type": "number"
                }
            }
        },
        "models.Pedido": {
            "type": "object",
            "properties": {
                "pedido_id": {
                    "type": "integer"
                },
                "produtos": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Produto"
                    }
                }
            }
        },
        "models.Produto": {
            "type": "object",
            "properties": {
                "dimensoes": {
                    "$ref": "#/definitions/models.Dimensoes"
                },
                "produto_id": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "API de Empacotamento",
	Description:      "API para empacotamento de produtos em caixas",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
